import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/bootstrap.css"
import Header from "./components/header/header";
import {ContextProvider} from './contexts/contextApi'
import Footer from "./components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Header/>
          {children}
          <Footer/>
        </ContextProvider>
      </body>
    </html>
  );
}
